### ISSUE TITLE
-x param

### ISSUE THREAD

**Issue by shafr** [azohra/shell-linter#47]
Please add an option for `-x` param.

I'm using a lot of 'source <>' in my code.

Locally I run it with:
```
shellcheck *.sh -x
```

When ran with this action, it fails instead. Not sure how to find walkaround.

**Comment by Azbagheri** [comment]
Hey @shafr,

This improvement was introduced in Shell Linter version [0.6.0](https://github.com/azohra/shell-linter/releases/tag/v0.6.0).  Please make sure you are running the latest version of the action by using:
```
- name: Run Shellcheck
  uses: azohra/shell-linter@latest
```

**Comment by shafr** [comment]
@Azbagheri and how can I pass that option / flag ? 
Is that enabled by default ? 
Thank you!

**Comment by Azbagheri** [comment]
Oh yes it is enabled by default.  Please give it a try and let me know how it goes.

**Comment by shafr** [comment]
For some reason it fails with:
```
 ^-------^ SC1091: Not following: util.sh: openBinaryFile: does not exist (No such file or directory)
```
this file exists & when running locally `shellcheck -x` it works fine.

**Comment by shafr** [comment]
Creating `.shellcheckrc` file with 
```
external-sources=true
source-path=src
```

resolved the issue
