### ISSUE TITLE
Support scripts with no extension

### ISSUE THREAD

**Issue by br0p0p** [azohra/shell-linter#8]
Hi, 

It would be great if this could support scripts that don't have the `.sh` extension. To make sure a file is actually a shell script, the executable permission could be checked, or ensure the shebang exists (or both).

**Comment by Azbagheri** [comment]
Hi @bropOp,

Thanks for reaching out! We think that's a great idea and we look into it for the next release!

**Comment by br0p0p** [comment]
@Azbagheri would you accept a PR for this?

**Comment by Azbagheri** [comment]
@br0p0p Thank you so much for your interest! However, I've already started working on it and it'll be published very soon! :)

**Comment by Azbagheri** [comment]
@br0p0p hey, we just released the new version of the action!! Shell Linter v0.2.0 supports scripts with no extension. Enjoy!
